version : '3.7'

services:
  phone-book:
    build: .
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      MONGO_HOST: mongo

  mongo:
    image: mongo:4.2.1-bionic
    ports:
      - 27017:27017
    volumes:
      - mongo-data-volume:/data/db
    env_file:
     - .env 

volumes:
  mongo-data-volume: