version : '3.7'

services:
  mongo:
    image: mongo:4.2.1-bionic
    ports:
      - 27017:27017
    volumes:
      - mongo-data-volume:/data/db
    env_file:
     - .env 

volumes:
  mongo-data-volume: